Remont_Kursovoi/Controllers/Типы_ремонтаController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Remont_Kursovoi;

namespace Remont_Kursovoi.Controllers
{
    public class Типы_ремонтаController : Controller
    {
        private Ремонт_оборудованияEntities db = new Ремонт_оборудованияEntities();

        // GET: Типы_ремонта
        [Authorize]
        public ActionResult Index()
        {
            var типы_ремонта = db.Типы_ремонта.Include(т => т.Типы_оборудования);
            return View(типы_ремонта.ToList());
        }

        // GET: Типы_ремонта/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Типы_ремонта типы_ремонта = db.Типы_ремонта.Find(id);
            if (типы_ремонта == null)
            {
                return HttpNotFound();
            }
            return View(типы_ремонта);
        }

        // GET: Типы_ремонта/Create
        public ActionResult Create()
        {
            ViewBag.ID_типа_оборудования = new SelectList(db.Типы_оборудования, "ID_типа_оборудования", "Наименование_типа");
            return View();
        }

        // POST: Типы_ремонта/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. 
        // Дополнительные сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Код_ремонта,Наименование,Периодичность,Длительность,ID_типа_оборудования")] Типы_ремонта типы_ремонта)
        {
            if (ModelState.IsValid)
            {
                db.Типы_ремонта.Add(типы_ремонта);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_типа_оборудования = new SelectList(db.Типы_оборудования, "ID_типа_оборудования", "Наименование_типа", типы_ремонта.ID_типа_оборудования);
            return View(типы_ремонта);
        }

        // GET: Типы_ремонта/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Типы_ремонта типы_ремонта = db.Типы_ремонта.Find(id);
            if (типы_ремонта == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_типа_оборудования = new SelectList(db.Типы_оборудования, "ID_типа_оборудования", "Наименование_типа", типы_ремонта.ID_типа_оборудования);
            return View(типы_ремонта);
        }

        // POST: Типы_ремонта/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. 
        // Дополнительные сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Код_ремонта,Наименование,Периодичность,Длительность,ID_типа_оборудования")] Типы_ремонта типы_ремонта)
        {
            if (ModelState.IsValid)
            {
                db.Entry(типы_ремонта).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_типа_оборудования = new SelectList(db.Типы_оборудования, "ID_типа_оборудования", "Наименование_типа", типы_ремонта.ID_типа_оборудования);
            return View(типы_ремонта);
        }

        // GET: Типы_ремонта/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Типы_ремонта типы_ремонта = db.Типы_ремонта.Find(id);
            if (типы_ремонта == null)
            {
                return HttpNotFound();
            }
            return View(типы_ремонта);
        }

        // POST: Типы_ремонта/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Типы_ремонта типы_ремонта = db.Типы_ремонта.Find(id);
            db.Типы_ремонта.Remove(типы_ремонта);
            try
            {
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Exception");
            }
            return View();
        }

        public ActionResult Exception()
        {
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Remont_Kursovoi/Views/Типы_ремонта/Create.cshtml
@model Remont_Kursovoi.Типы_ремонта

@{
    ViewBag.Title = "Create";
}



@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Типы ремонта</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.Код_ремонта,"Код ремонта", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Код_ремонта, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Код_ремонта, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Наименование, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Наименование, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Наименование, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Периодичность, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Периодичность, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Периодичность, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Длительность, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Длительность, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Длительность, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_типа_оборудования, "Тип оборудования", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_типа_оборудования", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_типа_оборудования, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>

Remont_Kursovoi/Views/Типы_ремонта/Delete.cshtml
@model Remont_Kursovoi.Типы_ремонта

@{
    ViewBag.Title = "Delete";
}



<h3>Вы уверены, что хотите удалить данную запись?</h3>
<div>
    <h4>Типы ремонта</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Наименование)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Наименование)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Периодичность)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Периодичность)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Длительность)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Длительность)
        </dd>

        <dt>
          Наименование типа
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Типы_оборудования.Наименование_типа)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
       <a class="btn btn-default" @Html.ActionLink("Назад", "Index")
        </div>
    }
</div>

Remont_Kursovoi/Views/Типы_ремонта/Details.cshtml
@model Remont_Kursovoi.Типы_ремонта

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Типы_ремонта</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Наименование)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Наименование)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Периодичность)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Периодичность)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Длительность)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Длительность)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Типы_оборудования.Наименование_типа)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Типы_оборудования.Наименование_типа)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Код_ремонта }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Remont_Kursovoi/Views/Типы_ремонта/Edit.cshtml
@model Remont_Kursovoi.Типы_ремонта

@{
    ViewBag.Title = "Edit";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Типы ремонта</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Код_ремонта)

        <div class="form-group">
            @Html.LabelFor(model => model.Наименование, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Наименование, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Наименование, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Периодичность, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Периодичность, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Периодичность, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Длительность, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Длительность, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Длительность, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_типа_оборудования, "Тип оборудования", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_типа_оборудования", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_типа_оборудования, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <p>
        <a class="btn btn-default" @Html.ActionLink("Назад", "Index")</p>
</div>

Remont_Kursovoi/Views/Типы_ремонта/Exception.cshtml
@{
    ViewBag.Title = "Exception";
}

<h2>Исключение!</h2>

<h2>
    Данный тип нельзя удалить т.к. имеются записи с этим типом данных.
    Пожалуйста удалите их, а затем попробуйте снова.
</h2>

<p><a class="btn btn-default" @Html.ActionLink("Назад", "Index", "Типы_ремонта")</p>

Remont_Kursovoi/Views/Типы_ремонта/Index.cshtml
@model IEnumerable<Remont_Kursovoi.Типы_ремонта>

@{
    ViewBag.Title = "Index";
}

<h2>Виды ремонтов на предприятии</h2>

<p>
   <a class="btn btn-default" @Html.ActionLink("Добавить запись", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Код ремонта
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Наименование)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Периодичность)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Длительность)
        </th>
        <th>
            Наименование типа
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Код_ремонта)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Наименование)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Периодичность)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Длительность)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Типы_оборудования.Наименование_типа)
    </td>
    <td>
        <p>
            <a class="btn btn-default" @Html.ActionLink("Редактировать", "Edit", new { id = item.Код_ремонта }) |
   <a class="btn btn-default" @Html.ActionLink("Удалить", "Delete", new { id = item.Код_ремонта })</p>
</td>
</tr>
}

</table>