Remont_Kursovoi/Controllers/Роли_работниковController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Remont_Kursovoi;

namespace Remont_Kursovoi.Controllers
{
    public class Роли_работниковController : Controller
    {
        private Ремонт_оборудованияEntities db = new Ремонт_оборудованияEntities();

        // GET: Роли_работников
        [Authorize]
        public ActionResult Index()
        {
            return View(db.Роли_работников.ToList());
        }

        // GET: Роли_работников/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Роли_работников роли_работников = db.Роли_работников.Find(id);
            if (роли_работников == null)
            {
                return HttpNotFound();
            }
            return View(роли_работников);
        }

        // GET: Роли_работников/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Роли_работников/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. 
        // Дополнительные сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Код_роли,Наименование")] Роли_работников роли_работников)
        {
            if (ModelState.IsValid)
            {
                db.Роли_работников.Add(роли_работников);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(роли_работников);
        }

        // GET: Роли_работников/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Роли_работников роли_работников = db.Роли_работников.Find(id);
            if (роли_работников == null)
            {
                return HttpNotFound();
            }
            return View(роли_работников);
        }

        // POST: Роли_работников/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. 
        // Дополнительные сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Код_роли,Наименование")] Роли_работников роли_работников)
        {
            if (ModelState.IsValid)
            {
                db.Entry(роли_работников).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(роли_работников);
        }

        // GET: Роли_работников/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Роли_работников роли_работников = db.Роли_работников.Find(id);
            if (роли_работников == null)
            {
                return HttpNotFound();
            }
            return View(роли_работников);
        }

        // POST: Роли_работников/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Роли_работников роли_работников = db.Роли_работников.Find(id);
            db.Роли_работников.Remove(роли_работников);
            try
            {
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Exception");
            }
            return View();

        }

        public ActionResult Exception()
        {
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Remont_Kursovoi/Views/Роли_работников/Create.cshtml
@model Remont_Kursovoi.Роли_работников

@{
    ViewBag.Title = "Create";
}



@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Роли работников</h4>
        <hr />
        @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Код_роли, "Код роли", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Код_роли, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Код_роли, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Наименование, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Наименование, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Наименование, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <p>
        <a class="btn btn-default" @Html.ActionLink("Назад", "Index")</p>
</div>

Remont_Kursovoi/Views/Роли_работников/Delete.cshtml
@model Remont_Kursovoi.Роли_работников

@{
    ViewBag.Title = "Delete";
}



<h3>Вы уверены, что хотите удалить эту информацию?</h3>
<div>
    <h4>Роли работников</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
           Роль
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Наименование)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
                <a class="btn btn-default" @Html.ActionLink("Назад", "Index")
</div>
    }
</div>

Remont_Kursovoi/Views/Роли_работников/Edit.cshtml
@model Remont_Kursovoi.Роли_работников

@{
    ViewBag.Title = "Edit";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Роли работников</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Код_роли)

        <div class="form-group">
            @Html.LabelFor(model => model.Наименование, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Наименование, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Наименование, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <p>
        <a class="btn btn-default" @Html.ActionLink("Назад", "Index")</p>
</div>

Remont_Kursovoi/Views/Роли_работников/Exception.cshtml
@{
    ViewBag.Title = "Exception";
}

<h2>Исключение!</h2>

<h2>
    Нельзя удалить т.к. имеются записи с этой ролью.
    Пожалуйста удалите их, а затем попробуйте снова.
</h2>

<p><a class="btn btn-default" @Html.ActionLink("Назад", "Index", "Роли_работников")</p>

Remont_Kursovoi/Views/Роли_работников/Index.cshtml
@model IEnumerable<Remont_Kursovoi.Роли_работников>

@{
    ViewBag.Title = "Index";
}

<h2>Роли работников</h2>


<p>
    <a class="btn btn-default" @Html.ActionLink("Добавить роль", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Роль
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Наименование)
            </td>
            <td>
                <p>
                    <a class="btn btn-default" @Html.ActionLink("Редактировать", "Edit", new { id = item.Код_роли }) |
   <a class="btn btn-default" @Html.ActionLink("Удалить", "Delete", new { id = item.Код_роли })</p>
</td>
        </tr>
    }

</table>