Remont_Kursovoi/Controllers/Типы_оборудованияController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Remont_Kursovoi;

namespace Remont_Kursovoi.Controllers
{
    public class Типы_оборудованияController : Controller
    {
        private Ремонт_оборудованияEntities db = new Ремонт_оборудованияEntities();

        [Authorize]
        public ActionResult Index()
        {
            return View(db.Типы_оборудования.ToList());
        }


        // GET: Типы_оборудования/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Типы_оборудования/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. 
        // Дополнительные сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_типа_оборудования,Наименование_типа")] Типы_оборудования типы_оборудования)
        {
            if (ModelState.IsValid)
            {
                типы_оборудования.ID_типа_оборудования = Guid.NewGuid();
                db.Типы_оборудования.Add(типы_оборудования);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(типы_оборудования);
        }

        // GET: Типы_оборудования/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Типы_оборудования типы_оборудования = db.Типы_оборудования.Find(id);
            if (типы_оборудования == null)
            {
                return HttpNotFound();
            }
            return View(типы_оборудования);
        }

        // POST: Типы_оборудования/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. 
        // Дополнительные сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_типа_оборудования,Наименование_типа")] Типы_оборудования типы_оборудования)
        {
            if (ModelState.IsValid)
            {
                db.Entry(типы_оборудования).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(типы_оборудования);
        }

        // GET: Типы_оборудования/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Типы_оборудования типы_оборудования = db.Типы_оборудования.Find(id);
            if (типы_оборудования == null)
            {
                return HttpNotFound();
            }
            return View(типы_оборудования);
        }


        // POST: Типы_оборудования/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Типы_оборудования типы_оборудования = db.Типы_оборудования.Find(id);
            db.Типы_оборудования.Remove(типы_оборудования);
            try
            {
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Exception");
            }
            
        }

        public ActionResult Exception()
        {
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        

    }
}

Remont_Kursovoi/Controllers/Экземпляры_оборудованийController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Remont_Kursovoi;
using Remont_Kursovoi.Models;

namespace Remont_Kursovoi.Controllers
{
    public class Экземпляры_оборудованийController : Controller
    {
        private Ремонт_оборудованияEntities db = new Ремонт_оборудованияEntities();

        // GET: Экземпляры_оборудований
        [Authorize]
        public ActionResult Index()
        {
            //var экземпляры_оборудований = db.Экземпляры_оборудований.Include(э => э.Состояние_оборудования).Include(э => э.Типы_оборудования);
            ViewBag.IdTypes = db.Типы_оборудования.ToList();
            return View(db.Экземпляры_оборудований.ToList());
        }

        // GET: Экземпляры_оборудований/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Экземпляры_оборудований экземпляры_оборудований = db.Экземпляры_оборудований.Find(id);
            if (экземпляры_оборудований == null)
            {
                return HttpNotFound();
            }
            return View(экземпляры_оборудований);
        }

        // GET: Экземпляры_оборудований/Create
        public ActionResult Create()
        {
            ViewBag.Код_состояния_оборудования = new SelectList(db.Состояние_оборудования, "Код_состояния_оборудования", "Наименование");
            ViewBag.ID_типа_оборудования = new SelectList(db.Типы_оборудования, "ID_типа_оборудования", "Наименование_типа");
            return View();
        }

        // POST: Экземпляры_оборудований/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. 
        // Дополнительные сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Код_экземпляра,Наименование,Код_состояния_оборудования,ID_типа_оборудования")] Экземпляры_оборудований экземпляры_оборудований)
        {
            if (ModelState.IsValid)
            {
                db.Экземпляры_оборудований.Add(экземпляры_оборудований);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Код_состояния_оборудования = new SelectList(db.Состояние_оборудования, "Код_состояния_оборудования", "Наименование", экземпляры_оборудований.Код_состояния_оборудования);
            ViewBag.ID_типа_оборудования = new SelectList(db.Типы_оборудования, "ID_типа_оборудования", "Наименование_типа", экземпляры_оборудований.ID_типа_оборудования);
            return View(экземпляры_оборудований);
        }

        [HttpPost]
        public ActionResult Index(Guid? IdTypes)
        {
            Ремонт_оборудованияEntities db = new Ремонт_оборудованияEntities();
            ViewBag.IdTypes = db.Типы_оборудования.ToList();

            var m = db.Экземпляры_оборудований;
            var c = m.ToList();

        if (IdTypes != null)
        {
          c = m.Where(a => a.ID_типа_оборудования == IdTypes).ToList();
        }

            return View(c);
        }




        // GET: Экземпляры_оборудований/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Экземпляры_оборудований экземпляры_оборудований = db.Экземпляры_оборудований.Find(id);
            if (экземпляры_оборудований == null)
            {
                return HttpNotFound();
            }
            ViewBag.Код_состояния_оборудования = new SelectList(db.Состояние_оборудования, "Код_состояния_оборудования", "Наименование", экземпляры_оборудований.Код_состояния_оборудования);
            ViewBag.ID_типа_оборудования = new SelectList(db.Типы_оборудования, "ID_типа_оборудования", "Наименование_типа", экземпляры_оборудований.ID_типа_оборудования);
            return View(экземпляры_оборудований);
        }

        // POST: Экземпляры_оборудований/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. 
        // Дополнительные сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Код_экземпляра,Наименование,Код_состояния_оборудования,ID_типа_оборудования")] Экземпляры_оборудований экземпляры_оборудований)
        {
            if (ModelState.IsValid)
            {
                db.Entry(экземпляры_оборудований).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Код_состояния_оборудования = new SelectList(db.Состояние_оборудования, "Код_состояния_оборудования", "Наименование", экземпляры_оборудований.Код_состояния_оборудования);
            ViewBag.ID_типа_оборудования = new SelectList(db.Типы_оборудования, "ID_типа_оборудования", "Наименование_типа", экземпляры_оборудований.ID_типа_оборудования);
            return View(экземпляры_оборудований);
        }

        // GET: Экземпляры_оборудований/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Экземпляры_оборудований экземпляры_оборудований = db.Экземпляры_оборудований.Find(id);
            if (экземпляры_оборудований == null)
            {
                return HttpNotFound();
            }
            return View(экземпляры_оборудований);
        }

        // POST: Экземпляры_оборудований/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Экземпляры_оборудований экземпляры_оборудований = db.Экземпляры_оборудований.Find(id);
            db.Экземпляры_оборудований.Remove(экземпляры_оборудований);
            try
            {
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Exception");
            }
        }

        public ActionResult Exception()
        {
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Remont_Kursovoi/Views/Типы_оборудования/Create.cshtml
@model Remont_Kursovoi.Типы_оборудования

@{
    ViewBag.Title = "Create";
}



@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Типы оборудования</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Наименование_типа,"Наименование типа", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Наименование_типа, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Наименование_типа, "Наименование типа", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <p><a class="btn btn-default"@Html.ActionLink("Назад", "Index")</p>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Remont_Kursovoi/Views/Типы_оборудования/Delete.cshtml
@model Remont_Kursovoi.Типы_оборудования

@{
    ViewBag.Title = "Delete";
}



<h3>Вы уверены что хотите удалить эту информацию?</h3>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            Наименование типа
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Наименование_типа)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" />
        </div>
    }
</div>
<div>
    <a class="btn btn-default" @Html.ActionLink("Назад", "Index")</a>
</div>

Remont_Kursovoi/Views/Типы_оборудования/Edit.cshtml
@model Remont_Kursovoi.Типы_оборудования

@{
    ViewBag.Title = "Edit";
}

<h2>Редактирование</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Типы оборудования</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_типа_оборудования)

        <div class="form-group">
            @Html.LabelFor(model => model.Наименование_типа, "Наименование типа", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Наименование_типа, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Наименование_типа, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
   <a class=" btn btn-default" @Html.ActionLink("Назад", "Index")</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Remont_Kursovoi/Views/Типы_оборудования/Exception.cshtml
@{
    ViewBag.Title = "Exception";
}

<h2>Исключение!</h2>

<h2>
    Нельзя удалить т.к. имеются записи с этим типом оборудования.
    Пожалуйста удалите их, а затем попробуйте снова.
</h2>

<p><a class="btn btn-default" @Html.ActionLink("Назад", "Index", "Типы_оборудования")</p>

Remont_Kursovoi/Views/Типы_оборудования/Index.cshtml
@model IEnumerable<Remont_Kursovoi.Типы_оборудования>

@{
    ViewBag.Title = "Index";
}



<h2>Типы оборудований</h2>
<p>
<a class="btn btn-default" @Html.ActionLink("Добавить тип", "Create")
</p>
<p>
    <a class="btn btn-default" @Html.ActionLink("Перейти к экземплярам", "Index", "Экземпляры_оборудований")
</p>

@*<p>
    <h4>
        Фильтровать по типу типу оборудования:
    </h4>
    @using (Html.BeginForm("Index", "Экземпляры"))
    {
<p>
    <select class="form-control" name="abc">
        <option value="0">Все</option>
        @foreach(var c in ViewBag.Cargos)
        {
        <option value=@c.ID_ТипаГруза>@c.ТипГруза</option>
        }
    </select>
    <input type="submit" value="Поиск" class="btn btn-default" />
</p>
}
</p>*@

<table class="table">
    <tr>
        <th>
            Наименование типа
        </th>
        <th></th>
    </tr>



    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Наименование_типа)
            </td>
            <td>
                <p>
                    <a class="btn btn-default" @Html.ActionLink("Редактировать", "Edit", new { id = item.ID_типа_оборудования }) |
                         <a class="btn btn-default"@Html.ActionLink("Удалить", "Delete", new { id = item.ID_типа_оборудования })</p>

</td>
        </tr>
    }

</table>

<a class=" btn btn-default" @Html.ActionLink("Назад", "Index", "Home")</a>

Remont_Kursovoi/Views/Типы_оборудования/action.cshtml
@model IEnumerable<Remont_Kursovoi.Типы_оборудования>
@{
    ViewBag.Title = "action";
}


@using (Html.BeginForm("action"))
    {
        <table>
            <tr>
                <td>
                    @Html.AntiForgeryToken()
                    @Html.DropDownList("ID_типа_оборудования", null, htmlAttributes: new { @class = "form-control" })
                </td>
                <td>

                    <input type="submit" value="Применить" class="btn btn-default " />
                </td>
            </tr>
        </table>
    }

Remont_Kursovoi/Views/Типы_оборудования/action2.cshtml
@model Remont_Kursovoi.Models.ЭкземплярыТипы
  

<br /><br />
       <div class="container">
           <div class="form-group">
               @if (ViewBag.ТипыList != null)
               {
                   @Html.DropDownListFor(model => model.ID_типа_оборудования, ViewBag.ТипыList as SelectList, "Типы", new { @class = "form-control" })

               }
           </div>

    <div class="form-group">
          
      @Html.DropDownListFor(model => model.Код_экземпляра, new SelectList(" "),"Экземпляры", new { @class = "form-control" })      
    </div>
</div>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script>
    $(document).ready(function () {
        $("#Id_типа_оборудования").change(function () {
            $.get("/Типы_оборудования/GetStateList", { Id_типа_оборудования: $("#Id_типа_оборудования").val() }, function (data) {
                $("#Код_экземпляра").empty();
                $.each(data, function (index, row) {
                    $("#Код_экземпляра").append("<option value='" + row.Код_экземпляра +"'>"+ row.Наименование +"</option>")

                });

            });
        })

    });
</script>