Remont_Kursovoi/Controllers/Журнал_выполненных_ремонтовController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Remont_Kursovoi;

namespace Remont_Kursovoi.Controllers
{
    public class Журнал_выполненных_ремонтовController : Controller
    {
        private Ремонт_оборудованияEntities db = new Ремонт_оборудованияEntities();

        // GET: Журнал_выполненных_ремонтов
        [Authorize]
        public ActionResult Index(Guid? id)
        {
            var журнал_выполненных_ремонтов = db.Журнал_выполненных_ремонтов.Include(ж => ж.График_плановых_техобслуживаний).Include(ж => ж.Экземпляры_оборудований).Include(ж => ж.Типы_ремонта);
            return View(журнал_выполненных_ремонтов.ToList());
        }

        // GET: Журнал_выполненных_ремонтов/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Журнал_выполненных_ремонтов журнал_выполненных_ремонтов = db.Журнал_выполненных_ремонтов.Find(id);
            if (журнал_выполненных_ремонтов == null)
            {
                return HttpNotFound();
            }
            return View(журнал_выполненных_ремонтов);
        }

        // GET: Журнал_выполненных_ремонтов/Create
        public ActionResult Create()
        {
            ViewBag.ID_планового_ремонта = new SelectList(db.График_плановых_техобслуживаний, "ID_планового_ремонта", "ID_планового_ремонта");
            ViewBag.Код_экземпляра = new SelectList(db.Экземпляры_оборудований, "Наименование", "Наименование");
            ViewBag.Код_ремонта = new SelectList(db.Типы_ремонта, "Наименование", "Наименование");
            return View();
        }

        // POST: Журнал_выполненных_ремонтов/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. 
        // Дополнительные сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_ремонта,Дата_начала,Дата_окончания,ID_планового_ремонта,Код_экземпляра,Код_ремонта,Примечания")] Журнал_выполненных_ремонтов журнал_выполненных_ремонтов)
        {
            if (ModelState.IsValid)
            {
                журнал_выполненных_ремонтов.ID_ремонта = Guid.NewGuid();
                db.Журнал_выполненных_ремонтов.Add(журнал_выполненных_ремонтов);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_планового_ремонта = new SelectList(db.График_плановых_техобслуживаний, "ID_планового_ремонта", "ID_планового_ремонта", журнал_выполненных_ремонтов.ID_планового_ремонта);
            ViewBag.Код_экземпляра = new SelectList(db.Экземпляры_оборудований, "Код_экземпляра", "Наименование", журнал_выполненных_ремонтов.Код_экземпляра);
            ViewBag.Код_ремонта = new SelectList(db.Типы_ремонта, "Код_ремонта", "Наименование", журнал_выполненных_ремонтов.Код_ремонта);
            return View(журнал_выполненных_ремонтов);
        }

        // GET: Журнал_выполненных_ремонтов/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Журнал_выполненных_ремонтов журнал_выполненных_ремонтов = db.Журнал_выполненных_ремонтов.Find(id);
            if (журнал_выполненных_ремонтов == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_планового_ремонта = new SelectList(db.График_плановых_техобслуживаний, "ID_планового_ремонта", "ID_планового_ремонта", журнал_выполненных_ремонтов.ID_планового_ремонта);
            ViewBag.Код_экземпляра = new SelectList(db.Экземпляры_оборудований, "Код_экземпляра", "Наименование", журнал_выполненных_ремонтов.Код_экземпляра);
            ViewBag.Код_ремонта = new SelectList(db.Типы_ремонта, "Код_ремонта", "Наименование", журнал_выполненных_ремонтов.Код_ремонта);
            return View(журнал_выполненных_ремонтов);
        }

        // POST: Журнал_выполненных_ремонтов/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. 
        // Дополнительные сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_ремонта,Дата_начала,Дата_окончания,ID_планового_ремонта,Код_экземпляра,Код_ремонта,Примечания")] Журнал_выполненных_ремонтов журнал_выполненных_ремонтов)
        {
            if (ModelState.IsValid)
            {
                db.Entry(журнал_выполненных_ремонтов).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_планового_ремонта = new SelectList(db.График_плановых_техобслуживаний, "ID_планового_ремонта", "ID_планового_ремонта", журнал_выполненных_ремонтов.ID_планового_ремонта);
            ViewBag.Код_экземпляра = new SelectList(db.Экземпляры_оборудований, "Код_экземпляра", "Наименование", журнал_выполненных_ремонтов.Код_экземпляра);
            ViewBag.Код_ремонта = new SelectList(db.Типы_ремонта, "Код_ремонта", "Наименование", журнал_выполненных_ремонтов.Код_ремонта);
            return View(журнал_выполненных_ремонтов);
        }

        // GET: Журнал_выполненных_ремонтов/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Журнал_выполненных_ремонтов журнал_выполненных_ремонтов = db.Журнал_выполненных_ремонтов.Find(id);
            if (журнал_выполненных_ремонтов == null)
            {
                return HttpNotFound();
            }
            return View(журнал_выполненных_ремонтов);
        }



        // POST: Журнал_выполненных_ремонтов/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        //[HandleError(ExceptionType = typeof(System.Data.Entity.Infrastructure.DbUpdateException))]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Журнал_выполненных_ремонтов журнал_выполненных_ремонтов = db.Журнал_выполненных_ремонтов.Find(id);
            db.Журнал_выполненных_ремонтов.Remove(журнал_выполненных_ремонтов);
            try
            {
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Exception");
            }
           
        }
        public ActionResult Exception()
        {
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Remont_Kursovoi/Controllers/РаботникиController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Remont_Kursovoi;

namespace Remont_Kursovoi.Controllers
{
    public class РаботникиController : Controller
    {
        private Ремонт_оборудованияEntities db = new Ремонт_оборудованияEntities();

        // GET: Работники

        [Authorize]
        public ActionResult Index()
        {
            return View(db.Работники.ToList());
            
        }

        [HttpPost]
        public ActionResult notlate_info(int number)
        {
            List<notlate_Result> notlate_Results = db.notlate(number).ToList();
            return View(notlate_Results);
        }



        // GET: Работники/Create
        public ActionResult LogUp()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LogUp([Bind(Include = "ID_работника,Должность,Фамилия,Имя,Отчество,Логин,Пароль")] Работники работники)
        {
            Random random = new Random();
            if (ModelState.IsValid)
            {
                Работники сотрудник = db.Работники.ToList().Find(x => x.Логин == работники.Логин);
                if (сотрудник == null)
                {
                    string Соль1 = Convert.ToString(random.Next(1000, 10000));
                    string hash = FormsAuthentication.HashPasswordForStoringInConfigFile(работники.Пароль + Соль1, "SHA1");
                    db.Работники.Add(new Работники
                    {
                        ID_работника = Guid.NewGuid(),
                        Должность = работники.Должность,
                        Фамилия = работники.Фамилия,
                        Имя = работники.Имя,
                        Отчество = работники.Отчество,
                        Пароль = hash,
                        Логин = работники.Логин,
                        Соль = Int32.Parse(Соль1)

                    });
                    db.SaveChanges();
                    сотрудник = db.Работники.ToList().Find(x => x.Логин == работники.Логин);
                    if (сотрудник != null)
                    {
                        FormsAuthentication.SetAuthCookie(работники.Логин, true);
                        return RedirectToAction("Index", "Home");
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Такой сотрудник уже зарегистрирован");
                }
            }
            return View();
        }


        // GET: Работники/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Работники работники = db.Работники.Find(id);
            if (работники == null)
            {
                return HttpNotFound();
            }
            return View(работники);
        }

        // POST: Работники/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. 
        // Дополнительные сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_работника,Должность,Фамилия,Имя,Отчество,Логин,Пароль")] Работники работники)
        {
            if (ModelState.IsValid)
            {
                db.Entry(работники).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(работники);
        }

        // GET: Работники/Delete/5
      
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Работники работники = db.Работники.Find(id);
            if (работники == null)
            {
                return HttpNotFound();
            }
            return View(работники);
        }
  

        // POST: Работники/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        
        public ActionResult DeleteConfirmed(Guid id)
        {
            Работники работники = db.Работники.Find(id);
            db.Работники.Remove(работники);
            try
            {
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch 
            {
                return RedirectToAction("Exception");
            }
           
        }

        public ActionResult Exception()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Actions()
        {
            return View();
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Remont_Kursovoi/Views/Журнал_выполненных_ремонтов/Create.cshtml
@model Remont_Kursovoi.Журнал_выполненных_ремонтов

@{
    ViewBag.Title = "Create";
}

<h2>Добавление записи о ремонте</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Журнал выполненных ремонтов</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Дата_начала, "Дата начала", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Дата_начала, new { htmlAttributes = new { @class = "form-control", @type = "Date" } })
                @Html.ValidationMessageFor(model => model.Дата_начала, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Дата_окончания, "Дата окончания", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Дата_окончания, new { htmlAttributes = new { @class = "form-control", @type = "Date" } })
                @Html.ValidationMessageFor(model => model.Дата_окончания, "", new { @class = "text-danger" })
            </div>
        </div>
       
        <div class="form-group">
            @Html.LabelFor(model => model.ID_планового_ремонта, "ID планового ремонта", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor( model => model.ID_планового_ремонта,"ID планового ремонта", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ID_планового_ремонта, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Код_экземпляра, "Экземпляр", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Код_экземпляра", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Код_экземпляра, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Код_ремонта,"Вид ремонта", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Код_ремонта", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Код_ремонта, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Примечания, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Примечания, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Примечания, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index","Home")
</div>

Remont_Kursovoi/Views/Журнал_выполненных_ремонтов/Delete.cshtml
@model Remont_Kursovoi.Журнал_выполненных_ремонтов

@{
    ViewBag.Title = "Delete";
}



<h3>Удалить эту запись о ремонте?</h3>
<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Дата начала
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Дата_начала)
        </dd>

        <dt>
            Дата окончания
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Дата_окончания)
        </dd>

        <dt>
            ID планового ремонта
        </dt>

        <dd>
            @Html.DisplayFor(model => model.График_плановых_техобслуживаний.ID_планового_ремонта)
        </dd>

        <dt>
            Экземпляр
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Экземпляры_оборудований.Наименование)
        </dd>

        <dt>
           Тип ремонта
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Типы_ремонта.Наименование)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Примечания)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Примечания)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
                <a class="btn btn-default" @Html.ActionLink("Назад", "Index")
</div>
    }
</div>

Remont_Kursovoi/Views/Журнал_выполненных_ремонтов/Details.cshtml
@model Remont_Kursovoi.Журнал_выполненных_ремонтов

<div>
    <h4>Журнал выполненных ремонтов</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
          Дата начала
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Дата_начала)
        </dd>

        <dt>
            Дата окончания
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Дата_окончания)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Примечания)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Примечания)
        </dd>

        <dt>
            Id планового ремонта
        </dt>

        <dd>
            @Html.DisplayFor(model => model.График_плановых_техобслуживаний.ID_планового_ремонта)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Экземпляры_оборудований.Наименование)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Экземпляры_оборудований.Наименование)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Типы_ремонта.Наименование)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Типы_ремонта.Наименование)
        </dd>

    </dl>
</div>
<p>
   <a class=" btn btn-default" @Html.ActionLink("Назад", "Index")
</p>

Remont_Kursovoi/Views/Журнал_выполненных_ремонтов/Edit.cshtml
@model Remont_Kursovoi.Журнал_выполненных_ремонтов

@{
    ViewBag.Title = "Edit";
}

<h2>Редактирование</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4></h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_ремонта)

        <div class="form-group">
            @Html.LabelFor(model => model.Дата_начала, "Дата начала",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Дата_начала, new { htmlAttributes = new { @class = "form-control", @type = "text" } })
                @Html.ValidationMessageFor(model => model.Дата_начала, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Дата_окончания, "Дата окончания", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Дата_окончания, new { htmlAttributes = new { @class = "form-control", @type ="text"} })
                @Html.ValidationMessageFor(model => model.Дата_окончания, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_планового_ремонта, "ID планового ремонта", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_планового_ремонта", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_планового_ремонта, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Код_экземпляра, "Экземпляр", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Код_экземпляра", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Код_экземпляра, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Код_ремонта, "Вид ремонта", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Код_ремонта", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Код_ремонта, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Примечания, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Примечания, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Примечания, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <p><a class=" btn btn-default"  @Html.ActionLink("Назад", "Index")</p>
</div>

Remont_Kursovoi/Views/Журнал_выполненных_ремонтов/Exception.cshtml
@{
    ViewBag.Title = "Exception";
}

<h2>Исключение!</h2>

<h2>
    Нельзя удалить т.к. имеются записи с данным ремонтом.
    Пожалуйста удалите их, а затем попробуйте снова.
</h2>

<p><a class="btn btn-default" @Html.ActionLink("Назад", "Index", "Работники")</p>

Remont_Kursovoi/Views/Журнал_выполненных_ремонтов/Index.cshtml
@model IEnumerable<Remont_Kursovoi.Журнал_выполненных_ремонтов>

@{
    ViewBag.Title = "Index";
}

<h2>Журнал выполненных ремонтов </h2>

<p>Внести запись в журнал выполненных ремонтов</p>
<p><a class="btn btn-default" @Html.ActionLink("Новая запись", "Create", "Журнал_выполненных_ремонтов")</a>
   <a class="btn btn-default" @Html.ActionLink("Работник в ремонте", "Index", "Работник_в_ремонте1")</a>
</p>

<table class="table">
    <tr>
        <th>
            Дата начала
        </th>
        <th>
            Дата окончания
        </th>
        <th>
            Экземпляр
        </th>
        <th>
            Тип ремонта
        </th>
        <th>
            Примечания
        </th>
        <th></th>
        <th></th>
        <th></th>

    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Дата_начала)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Дата_окончания)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Экземпляры_оборудований.Наименование)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Типы_ремонта.Наименование)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Примечания)
    </td>
    <td>
        <a class="btn btn-default" @Html.ActionLink("Редактировать", "Edit", new { id = item.ID_ремонта })
    </td>
    <td>
        <a class="btn btn-default" @Html.ActionLink("Удалить", "Delete", new { id = item.ID_ремонта })
    </td>
    <td>
        <a class="btn btn-default" @Html.ActionLink("Детали", "Details", new { id = item.ID_ремонта })
    </td>
</tr>
    }

</table>